MCC18(1)                                                              MCC18(1)



NNAAMMEE
       MCC18 - MicroChip(tm) C compiler for PIC processors




SSYYNNOOPPSSIISS
       mcc18 [flags] file.c
       mpasm [flags] file.asm
       mplib [flags] files
       mplink [flags] files


DDEESSCCRRIIPPTTIIOONN
       MCC18  is Microchips's commercial compiler for PIC processors, distrib-
       uted only for Windows.

       In order to use MCC18 on Unix, you will need  an  Intel  processor  and
       Wine, or an Intel PC emulator such as VirtualPC or QEMU.

       This  port  uses  wrapper scripts and Wine to make the MCC tools appear
       native on Intel Unix systems.

       For quick help, just type any of the commands with no arguments.


SSEEEE AALLSSOO
       Wine(1), sdcc(1)


AAUUTTHHOORR
       Jason W. Bacon
       Acadix Consulting, LLC




                                                                      MCC18(1)
